[package]
name = "pvsecret"
version = "0.9.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "1", features = ["std"] }
clap = { version ="4", features = ["derive", "wrap_help"]}
log = { version = "0.4", features = ["std", "release_max_level_debug"] }
serde_yaml = "0.9"

pv = { path = "../pv", features = ["uvsecret", "request"] }
utils = { path = "../utils" }
