[package]
name = "pv"
version = "0.9.1"
edition.workspace = true
license.workspace = true

[dependencies]
byteorder = "1.3"
clap = { version ="4", features = ["derive", "wrap_help"] }
curl = "0.4.7"
log = { version = "0.4.6", features = ["std", "release_max_level_debug"] }
openssl = "0.10.49"
serde = { version = "1.0.139", features = ["derive"]  }
thiserror = "1.0.33"
utils = {path = "../utils"}
zerocopy = "0.6"

openssl_extensions = { path = "openssl_extensions" }
pv_core = { path = "../pv_core" }

[dev-dependencies]
mockito = {version = "1", default-features = false }
serde_test = "1"
lazy_static = "1.1"
